import { IArticle } from "@customTypes/articleTypes";

export const mockArticles: IArticle[] = [
  {
    id: "1",
    title: "Заголовок 1",
    sport: "Футбол",
    content: "Содержание 1",
    description: "Описание 1",
    author: {
      id: "author1",
      firstName: "Имя1",
      lastName: "Фамилия1",
    },
    image: "https://picsum.photos/1920/1080",
    tags: ["тег1", "тег2"],
    likeCount: 10,
    status: "published",
    updatedAt: "2023-09-15",
    createdAt: "2023-09-14",
  },
  {
    id: "2",
    title: "Заголовок 2",
    sport: "Футбол",
    content: "Содержание 2",
    description: "Описание 2",
    author: {
      id: "author2",
      firstName: "Имя2",
      lastName: "Фамилия2",
    },
    image: "https://picsum.photos/1920/1080",
    tags: ["тег3", "тег4"],
    likeCount: 15,
    status: "published",
    updatedAt: "2023-09-16",
    createdAt: "2023-09-13",
  },
  {
    id: "3",
    title: "Заголовок 3",
    sport: "Баскетбол",
    content: "Содержание 3",
    description: "Описание 3",
    author: {
      id: "author3",
      firstName: "Имя3",
      lastName: "Фамилия3",
    },
    image: "https://picsum.photos/1920/1080",
    tags: ["тег5", "тег6"],
    likeCount: 20,
    status: "draft",
    updatedAt: "2023-09-14",
    createdAt: "2023-09-12",
  },
  {
    id: "4",
    title: "Заголовок 4",
    sport: "Теннис",
    content: "Содержание 4",
    description: "Описание 4",
    author: {
      id: "author4",
      firstName: "Имя4",
      lastName: "Фамилия4",
    },
    image: "https://picsum.photos/1920/1080",
    tags: ["тег7", "тег8"],
    likeCount: 5,
    status: "published",
    updatedAt: "2023-09-17",
    createdAt: "2023-09-11",
  },
  {
    id: "5",
    title: "Заголовок 5",
    sport: "Баскетбол",
    content: "Содержание 5",
    description: "Описание 5",
    author: {
      id: "author5",
      firstName: "Имя5",
      lastName: "Фамилия5",
    },
    image: "https://picsum.photos/1920/1080",
    tags: ["тег9", "тег10"],
    likeCount: 8,
    status: "published",
    updatedAt: "2023-09-18",
    createdAt: "2023-09-10",
  },
  {
    id: "6",
    title: "Заголовок 6",
    sport: "Футбол",
    content: "Содержание 6",
    description: "Описание 6",
    author: {
      id: "author6",
      firstName: "Имя6",
      lastName: "Фамилия6",
    },
    image: "https://picsum.photos/1920/1080",
    tags: ["тег11", "тег12"],
    likeCount: 12,
    status: "draft",
    updatedAt: "2023-09-19",
    createdAt: "2023-09-09",
  },
  {
    id: "7",
    title: "Заголовок 7",
    sport: "Теннис",
    content: "Содержание 7",
    description: "Описание 7",
    author: {
      id: "author7",
      firstName: "Имя7",
      lastName: "Фамилия7",
    },
    image: "https://picsum.photos/1920/1080",
    tags: ["тег13", "тег14"],
    likeCount: 18,
    status: "published",
    updatedAt: "2023-09-20",
    createdAt: "2023-09-08",
  },
];
